"""Opt-in experimental adapters that remain outside the stable API."""

from lowbit_comm.experimental.compatibility import (
    RSAG_CUDA_EXTENSION_ABI,
    RSAG_LOWBIT_COMM_VERSION,
    RSAG_VERIFIED_RUNTIME_MATRIX,
    RSAGCompatibilityReport,
    RSAGRuntimeABI,
    compute_rsag_build_fingerprint,
    is_verified_rsag_runtime,
    probe_rsag_compatibility,
)
from lowbit_comm.experimental.rsag import (
    RSAG_CHECKPOINT_SCHEMA_VERSION,
    RSAG_EVIDENCE_SCHEMA_VERSION,
    CommittedResidual,
    QWDSchedule,
    RouteDecision,
    RSAGEnvironment,
    RSAGEvidence,
    RSAGQWDAdapter,
    RSAGQWDPlans,
    ShardLayout,
    ShardedAdamW,
    copy_flat_to_parameters,
    detect_rsag_environment,
    flatten_parameter_copy,
    select_rsag_route,
)


__all__ = (
    "RSAG_CHECKPOINT_SCHEMA_VERSION",
    "RSAG_CUDA_EXTENSION_ABI",
    "RSAG_EVIDENCE_SCHEMA_VERSION",
    "RSAG_LOWBIT_COMM_VERSION",
    "RSAG_VERIFIED_RUNTIME_MATRIX",
    "RSAGCompatibilityReport",
    "RSAGRuntimeABI",
    "CommittedResidual",
    "QWDSchedule",
    "RouteDecision",
    "RSAGEnvironment",
    "RSAGEvidence",
    "RSAGQWDAdapter",
    "RSAGQWDPlans",
    "ShardLayout",
    "ShardedAdamW",
    "copy_flat_to_parameters",
    "compute_rsag_build_fingerprint",
    "detect_rsag_environment",
    "flatten_parameter_copy",
    "is_verified_rsag_runtime",
    "probe_rsag_compatibility",
    "select_rsag_route",
)
